# Generated by Django 4.2.21 on 2025-05-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='choix_contact',
            field=models.BooleanField(default=True, null=None),
        ),
    ]
